site_name: Live Tracking
nav:
- 'About': index.md
- 'Installation': Install.md
- 'API':
  - 'Getting started': Getting-started.md
  - 'New User':
    - 'Create User (Register)': Create-User-Register.md
  - 'User Data':
    - 'Get User List': Get-User-List.md
    - 'Get User Data': Get-User-Data.md
  - 'Edit User':
    - 'Change Password': Change-Password.md
    - 'Delete User': Delete-User.md
  - 'Live Tracking':
    - 'Writing Data': Writing-Data.md
    - 'Querying Data': Querying-Data.md
- 'Imprint': Imprint.md
use_directory_urls: false
repo_url: https://github.com/livetracking/docu
theme:
  language: 'en'
  name: 'material'
  favicon: 'img/favicon.ico'
  logo: 'img/logo.png'
  palette:
    primary: 'white'
    accent: 'black'
