name: Deploy MkDocs

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v3
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install rsync python3-pip -y
    - name: Install MkDocs
      run: |
        pip3 install --upgrade setuptools
        pip3 install mkdocs
        pip3 install mkdocs-material
        pip3 install mkdocs-minify-plugin
    - name: Build docs
      run: $HOME/.local/bin/mkdocs build
    - name: CNAME
      run: echo 'livetracking.nkn-it.de' > "site/CNAME"
    # https://github.com/marketplace/actions/deploy-to-github-pages
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: site
